export interface Country {
  name: string;
  iso: string;
  code: string;
  flag: string;
}

export const COUNTRIES: Country[] = [
  { name: "India", iso: "IN", code: "+91", flag: "🇮🇳" },
  { name: "United States", iso: "US", code: "+1", flag: "🇺🇸" },
  { name: "United Kingdom", iso: "GB", code: "+44", flag: "🇬🇧" },
  { name: "Canada", iso: "CA", code: "+1", flag: "🇨🇦" },
  { name: "Australia", iso: "AU", code: "+61", flag: "🇦🇺" },
  { name: "United Arab Emirates", iso: "AE", code: "+971", flag: "🇦🇪" },
  { name: "Saudi Arabia", iso: "SA", code: "+966", flag: "🇸🇦" },
  { name: "Qatar", iso: "QA", code: "+974", flag: "🇶🇦" },
  { name: "Kuwait", iso: "KW", code: "+965", flag: "🇰🇼" },
  { name: "Oman", iso: "OM", code: "+968", flag: "🇴🇲" },
  { name: "Bahrain", iso: "BH", code: "+973", flag: "🇧🇭" },
  { name: "Singapore", iso: "SG", code: "+65", flag: "🇸🇬" },
  { name: "Malaysia", iso: "MY", code: "+60", flag: "🇲🇾" },
  { name: "Germany", iso: "DE", code: "+49", flag: "🇩🇪" },
  { name: "France", iso: "FR", code: "+33", flag: "🇫🇷" },
  { name: "Italy", iso: "IT", code: "+39", flag: "🇮🇹" },
  { name: "Spain", iso: "ES", code: "+34", flag: "🇪🇸" },
  { name: "Netherlands", iso: "NL", code: "+31", flag: "🇳🇱" },
  { name: "Switzerland", iso: "CH", code: "+41", flag: "🇨🇭" },
  { name: "New Zealand", iso: "NZ", code: "+64", flag: "🇳🇿" },
  { name: "South Africa", iso: "ZA", code: "+27", flag: "🇿🇦" },
  { name: "Nigeria", iso: "NG", code: "+234", flag: "🇳🇬" },
  { name: "Kenya", iso: "KE", code: "+254", flag: "🇰🇪" },
  { name: "Brazil", iso: "BR", code: "+55", flag: "🇧🇷" },
  { name: "Mexico", iso: "MX", code: "+52", flag: "🇲🇽" },
  { name: "Japan", iso: "JP", code: "+81", flag: "🇯🇵" },
  { name: "South Korea", iso: "KR", code: "+82", flag: "🇰🇷" },
  { name: "China", iso: "CN", code: "+86", flag: "🇨🇳" },
  { name: "Hong Kong", iso: "HK", code: "+852", flag: "🇭🇰" },
  { name: "Philippines", iso: "PH", code: "+63", flag: "🇵🇭" },
  { name: "Indonesia", iso: "ID", code: "+62", flag: "🇮🇩" },
  { name: "Thailand", iso: "TH", code: "+66", flag: "🇹🇭" },
  { name: "Vietnam", iso: "VN", code: "+84", flag: "🇻🇳" },
  { name: "Pakistan", iso: "PK", code: "+92", flag: "🇵🇰" },
  { name: "Bangladesh", iso: "BD", code: "+880", flag: "🇧🇩" },
  { name: "Sri Lanka", iso: "LK", code: "+94", flag: "🇱🇰" },
  { name: "Nepal", iso: "NP", code: "+977", flag: "🇳🇵" },
  { name: "Ireland", iso: "IE", code: "+353", flag: "🇮🇪" },
  { name: "Sweden", iso: "SE", code: "+46", flag: "🇸🇪" },
  { name: "Norway", iso: "NO", code: "+47", flag: "🇳🇴" },
  { name: "Denmark", iso: "DK", code: "+45", flag: "🇩🇰" },
  { name: "Finland", iso: "FI", code: "+358", flag: "🇫🇮" },
  { name: "Belgium", iso: "BE", code: "+32", flag: "🇧🇪" },
  { name: "Austria", iso: "AT", code: "+43", flag: "🇦🇹" },
  { name: "Portugal", iso: "PT", code: "+351", flag: "🇵🇹" },
  { name: "Greece", iso: "GR", code: "+30", flag: "🇬🇷" },
  { name: "Turkey", iso: "TR", code: "+90", flag: "🇹🇷" },
  { name: "Egypt", iso: "EG", code: "+20", flag: "🇪🇬" },
  { name: "Israel", iso: "IL", code: "+972", flag: "🇮🇱" },
];
